name: Build & Publish To Windows

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-and-publish-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Publish to GitHub Release
        permissions: write-all
        run: npm run publish 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
